#!/usr/bin/env python3

import argparse
import json
import os
import re
import sys
import zipfile

from data_log import DataLog
from motec_log import MotecLog

DESCRIPTION = """Generates MoTeC .ld files from external log files generated by: CAN bus dumps, CSV
 files, COBB Accessport CSV files, or RaceChrono CSV files"""

EPILOG = """The CAN bus log must be the same format as what is generated by 'candump' with the '-l'
option from the linux package can-utils. A MoTeC channel will be created for every signal in the
DBC file that has messages in the CAN log. The signal name and units will be directly copied from
the DBC file.

CSV files must have time as their first column. A MoTeC channel will be generated for all remaining
columns. All channels will not have any units assigned.

COBB Accessport CSV logs are simply generated by starting a logging session on the accessport. A
MoTeC channel will be created for every channel logged, the name and units will be directly copied
over.

RaceChrono CSV files are parsed looking for the 'Time (s)' header row and mapped to standard MoTeC
channel names and units automatically where applicable.
"""


def _get_stints(rcz_path):
    with zipfile.ZipFile(rcz_path, 'r') as z:
        if "session.json" in z.namelist():
            session_json = json.loads(z.read("session.json").decode("utf-8"))
            laps = session_json.get("laps", [])
            return sorted(set(lap.get("sessionResume", 0) for lap in laps))
    return [0]


VENUE_NORMALIZE = {
    "thunderhill raceway park": "Thunderhill Raceway Park",
    "thunder hill raceway park": "Thunderhill Raceway Park",
    "thunderhill": "Thunderhill Raceway Park",
    "thunder hill": "Thunderhill Raceway Park",
    "thill": "Thunderhill Raceway Park",
    "laguna seca": "Laguna Seca",
    "laguna": "Laguna Seca",
    "sonoma raceway": "Sonoma Raceway",
    "sonoma": "Sonoma Raceway",
}


def _normalize_venue(name):
    if not name:
        return name
    clean_name = name.replace(".csv", "").replace(".rcz", "").replace(",", " ")
    lower_search = clean_name.lower().replace("_", " ").replace("-", " ")

    for key in sorted(VENUE_NORMALIZE.keys(), key=len, reverse=True):
        if key in lower_search:
            canonical = VENUE_NORMALIZE[key]
            idx = lower_search.index(key) + len(key)
            raw_suffix = clean_name.replace("_", " ").replace("-", " ")[idx:].strip()

            # Truncate at common filename separators
            raw_suffix = re.split(r"\s+-\s+|\s+_\s+|\s+\d{4}\b", raw_suffix)[0].strip()

            # Clean up generic track suffix words if canonical already contains them
            for generic in ["raceway park", "raceway", "park", "track", "seca"]:
                if raw_suffix.lower().startswith(generic):
                    raw_suffix = raw_suffix[len(generic):].strip()

            # Clean up trailing file artifacts
            raw_suffix = re.sub(r"\blap\s*\d+.*$", "", raw_suffix, flags=re.IGNORECASE).strip()
            raw_suffix = re.sub(r"\bv\d+.*$", "", raw_suffix, flags=re.IGNORECASE).strip()
            raw_suffix = re.sub(r"\bstint\s*\d+.*$", "", raw_suffix, flags=re.IGNORECASE).strip()

            suffix = " ".join(raw_suffix.split())
            for abbr, full in [("EST", "East"), ("BY", "Bypass"), ("EB", "East Bypass"),
                                ("CCW", "CCW"), ("CW", "CW")]:
                suffix = re.sub(r"\b" + abbr + r"\b", full, suffix, flags=re.IGNORECASE)

            suffix = " ".join(suffix.split())
            if suffix:
                formatted_suffix = suffix.title() if (suffix.islower() or suffix.isupper()) and len(suffix) > 3 else suffix
                return f"{canonical} ({formatted_suffix})"
            return canonical
    return name


def _process_one(args, stint_override=None, output_override=None):
    stint_arg = stint_override if stint_override is not None else args.stint
    out_base = output_override if output_override is not None else args.output

    print("Loading log...")
    data_log = DataLog()

    if args.log_type == "CAN":
        try:
            import cantools
        except ImportError:
            print("ERROR: 'cantools' package is required for CAN log processing.")
            print("  Install with: pip install cantools")
            sys.exit(1)

        with open(args.log, "r") as file:
            lines = file.readlines()

        if not os.path.isfile(args.dbc):
            print("ERROR: DBC file %s does not exist" % args.dbc)
            sys.exit(1)

        print("Loading DBC...")
        can_db = cantools.database.load_file(args.dbc)

        print("Extracting data...")
        data_log.from_can_log(lines, can_db)
    elif args.log_type == "CSV":
        with open(args.log, "r") as file:
            lines = file.readlines()
        print("Extracting data...")
        data_log.from_csv_log(lines, target_lap=args.lap)
    elif args.log_type == "ACCESSPORT":
        with open(args.log, "r") as file:
            lines = file.readlines()
        print("Extracting data...")
        data_log.from_accessport_log(lines)
    elif args.log_type == "RACECHRONO":
        with open(args.log, "r") as file:
            lines = file.readlines()
        print("Extracting data...")
        data_log.from_racechrono_log(lines, target_lap=args.lap)
    elif args.log_type == "RCZ":
        print("Extracting RCZ data directly...")
        data_log.from_rcz_log(args.log, target_lap=args.lap,
                              target_stint=stint_arg, min_lap_sec=args.min_lap_sec)

    if not data_log.channels:
        print("ERROR: Failed to find any channels in log data")
        sys.exit(1)

    print("Parsed %.1fs log with %s channels:" % (data_log.duration(), len(data_log.channels)))
    for channel_name, channel in data_log.channels.items():
        print("\t%s" % channel)

    resample_freq = data_log.resample(args.frequency)
    print("Resampled channels at %.1f Hz..." % resample_freq)

    print("Calculating advanced math channels...")
    data_log.calculate_math_channels()

    print("Converting to MoTeC log...")

    meta = getattr(data_log, "metadata", {})

    venue_name = args.venue_name if args.venue_name else meta.get("venue_name", "")
    if not venue_name and hasattr(data_log, "rcz_metadata") and data_log.rcz_metadata.get("trackName"):
        venue_name = data_log.rcz_metadata.get("trackName")

    if not venue_name:
        filename = os.path.basename(args.log)
        venue_name = _normalize_venue(filename)
        if venue_name == filename:
            venue_name = _normalize_venue(meta.get("event_session", meta.get("Session", "")))
    else:
        venue_name = _normalize_venue(venue_name)

    event_name = args.event_name if args.event_name else meta.get("event_name", "")
    if not event_name and venue_name:
        event_name = venue_name.replace("_", " ").title() + " Track Day" if not venue_name.endswith("Track Day") else venue_name

    driver_name = args.driver if args.driver else meta.get("driver", meta.get("Racer", ""))
    if not driver_name:
        driver_name = "Unknown Driver"

    vehicle_name = args.vehicle_id if args.vehicle_id else meta.get("vehicle_id", meta.get("Vehicle", ""))

    motec_log = MotecLog()
    if getattr(data_log, "datetime", None):
        motec_log.datetime = data_log.datetime
    motec_log.driver = driver_name
    motec_log.vehicle_id = vehicle_name
    motec_log.vehicle_weight = args.vehicle_weight
    motec_log.vehicle_type = args.vehicle_type
    motec_log.vehicle_comment = args.vehicle_comment
    motec_log.venue_name = venue_name
    motec_log.event_name = event_name
    motec_log.event_session = args.event_session if args.event_session else meta.get("event_session", "")
    motec_log.long_comment = args.long_comment if args.long_comment else meta.get("long_comment", meta.get("Comment", ""))
    motec_log.short_comment = args.short_comment if args.short_comment else meta.get("short_comment", "")

    motec_log.initialize()
    motec_log.add_all_channels(data_log)

    print("Saving MoTeC log...")
    if out_base:
        ld_filename = os.path.splitext(out_base)[0] + ".ld"
    else:
        candump_dir, candump_filename = os.path.split(args.log)
        candump_filename = os.path.splitext(candump_filename)[0]
        ld_filename = os.path.join(candump_dir, candump_filename + ".ld")

    ldx_filename = os.path.splitext(ld_filename)[0] + ".ldx"

    output_dir = os.path.dirname(ld_filename)
    if output_dir and not os.path.isdir(output_dir):
        print("Directory '%s' does not exist, will create it" % output_dir)
        os.makedirs(output_dir)

    motec_log.write(ld_filename)
    beacons = data_log.detect_beacons()
    motec_log.write_ldx(ldx_filename, getattr(data_log, "laps_info", None), beacons=beacons)
    print("Saved .ld file: %s" % ld_filename)
    print("Saved .ldx file: %s" % ldx_filename)

    if args.gpx:
        gpx_filename = os.path.splitext(ld_filename)[0] + ".gpx"
        if motec_log.write_gpx(gpx_filename, data_log):
            print("Saved .gpx track file: %s" % gpx_filename)

    if args.kml:
        kml_filename = os.path.splitext(ld_filename)[0] + ".kml"
        if motec_log.write_kml(kml_filename, data_log):
            print("Saved .kml Google Earth file: %s" % kml_filename)

    print("Done!")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=DESCRIPTION, epilog=EPILOG)
    parser.add_argument("log", type=str, help="Path to logfile")
    parser.add_argument("log_type", type=str, help="Type of log to process",
                        choices=["CAN", "CSV", "ACCESSPORT", "RACECHRONO", "RCZ"])

    parser.add_argument("--output", type=str,
                        help="Name of output file, defaults to the same filename as 'log'")
    parser.add_argument("--frequency", type=str, default="auto",
                        help="Fixed frequency to resample all channels at (e.g. 20, 25, 50, 100 or 'auto', default: auto)")
    parser.add_argument("--gpx", action="store_true", help="Also generate GPX track file")
    parser.add_argument("--kml", action="store_true", help="Also generate KML Google Earth track file")
    parser.add_argument("--dbc", type=str, help="Path to DBC file, required if log type CAN")

    parser.add_argument("--lap", type=str, default="all",
                        help="Specific lap number to export (e.g. 1, 15) or 'all' to export all laps. Default is 'all'")
    parser.add_argument("--stint", type=str, default="all",
                        help="RCZ sessionResume stint to export")
    parser.add_argument("--min_lap_sec", type=float, default=15.0,
                        help="Minimum valid lap duration in seconds to filter noise (default: 15.0)")
    parser.add_argument("--driver", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--vehicle_id", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--vehicle_weight", type=int, default=0, help="Motec log metadata field")
    parser.add_argument("--vehicle_type", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--vehicle_comment", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--venue_name", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--event_name", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--event_session", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--long_comment", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--short_comment", type=str, default="", help="Motec log metadata field")
    args = parser.parse_args()

    if str(args.frequency).lower() != "auto":
        try:
            if float(args.frequency) <= 0:
                print("ERROR: --frequency must be positive or 'auto'")
                sys.exit(1)
        except ValueError:
            print("ERROR: Invalid --frequency value '%s'. Must be a number or 'auto'" % args.frequency)
            sys.exit(1)

    if args.log:
        args.log = os.path.expanduser(args.log)
    if args.dbc:
        args.dbc = os.path.expanduser(args.dbc)
    if args.output:
        args.output = os.path.expanduser(args.output)

    if args.log.lower().endswith(".rcz") and args.log_type != "RCZ":
        print("WARNING: Overriding --log_type '%s' to 'RCZ' because input file has .rcz extension" % args.log_type)
        args.log_type = "RCZ"

    if not os.path.isfile(args.log):
        print("ERROR: log file %s does not exist" % args.log)
        sys.exit(1)

    if args.log_type == "CAN" and not os.path.isfile(args.dbc):
        print("ERROR: DBC file %s does not exist" % args.dbc)
        sys.exit(1)

    if args.log_type == "RCZ" and str(args.stint).lower() == "all":
        try:
            stints = _get_stints(args.log)
        except Exception as e:
            print("ERROR: Failed to read RCZ stints: %s" % e)
            sys.exit(1)

        if len(stints) > 1:
            print("Auto-detected %d stints in RCZ log: %s" % (len(stints), stints))
            base_output = args.output if args.output else args.log
            base_name, ext = os.path.splitext(base_output)
            for st in stints:
                st_out = f"{base_name}_stint{st}"
                print("\n=== Exporting Stint %s -> %s ===" % (st, st_out))
                _process_one(args, stint_override=str(st), output_override=st_out)
            print("Auto-stint split export complete.")
            sys.exit(0)

    _process_one(args)
